### ISSUE TITLE
test-support types not found after upgrade to 7.0.0

### ISSUE THREAD

**Issue by dagroe** [ember-lifeline/ember-lifeline#1176]
After upgrading to `7.0.0` I get a TypeScript error in tests when importing from `ember-lifeline/test-support`.

E.g. in `tests/integration/components/component-1-test.ts` I get error 

`Cannot find module 'ember-lifeline/test-support' or its corresponding type declarations.`

for import

```typescript
import { pollTaskFor } from 'ember-lifeline/test-support';
```

Do I need to change those imports?
